import json

products = [
    dict(sku="SHOE-001", brand="Nike", name="Air Zoom Pegasus 40", type="sport", color="black",
         price=8999, sizes=[(7,5),(8,8),(9,6),(10,3)],
         description="Everyday running shoe with responsive cushioning, built for daily training miles.",
         tags=["running", "training", "everyday", "cushioned"]),
    dict(sku="SHOE-002", brand="Nike", name="Court Vision Low", type="casual", color="white",
         price=5499, sizes=[(6,4),(7,7),(8,9),(9,5)],
         description="Retro basketball-inspired low-top sneaker for everyday casual wear.",
         tags=["sneaker", "streetwear", "everyday", "retro"]),
    dict(sku="SHOE-003", brand="Adidas", name="Ultraboost Light", type="sport", color="blue",
         price=14999, sizes=[(7,3),(8,6),(9,4),(10,2)],
         description="Premium performance running shoe with high energy-return Boost midsole.",
         tags=["running", "performance", "premium", "cushioned"]),
    dict(sku="SHOE-004", brand="Adidas", name="Samba OG", type="casual", color="white/green",
         price=8499, sizes=[(6,5),(7,8),(8,7),(9,4)],
         description="Iconic low-profile leather sneaker, a streetwear staple.",
         tags=["sneaker", "streetwear", "iconic", "leather"]),
    dict(sku="SHOE-005", brand="Puma", name="Velocity Nitro 3", type="sport", color="orange",
         price=7999, sizes=[(7,6),(8,5),(9,3)],
         description="Lightweight nitrogen-infused running shoe for speed workouts.",
         tags=["running", "lightweight", "speed", "training"]),
    dict(sku="SHOE-006", brand="Puma", name="Suede Classic", type="casual", color="maroon",
         price=4999, sizes=[(6,9),(7,6),(8,4)],
         description="Classic suede sneaker with a timeless silhouette, great for everyday styling.",
         tags=["sneaker", "casual", "classic", "suede"]),
    dict(sku="SHOE-007", brand="Reebok", name="Nano X4", type="sport", color="grey",
         price=9999, sizes=[(7,4),(8,5),(9,6),(10,2)],
         description="Cross-training shoe built for gym workouts, lifting, and HIIT sessions.",
         tags=["training", "gym", "crossfit", "stable"]),
    dict(sku="SHOE-008", brand="Reebok", name="Classic Leather", type="casual", color="white",
         price=5999, sizes=[(6,7),(7,8),(8,6)],
         description="Minimalist all-white leather sneaker that pairs with almost anything.",
         tags=["sneaker", "casual", "minimalist", "leather"]),
    dict(sku="SHOE-009", brand="New Balance", name="990v6", type="sport", color="grey/navy",
         price=16999, sizes=[(7,3),(8,4),(9,2)],
         description="Made-in-USA premium running shoe known for comfort and craftsmanship.",
         tags=["running", "premium", "comfort", "everyday"]),
    dict(sku="SHOE-010", brand="New Balance", name="574 Core", type="casual", color="green",
         price=7499, sizes=[(6,5),(7,6),(8,5)],
         description="Retro-running-style sneaker, a versatile everyday casual pick.",
         tags=["sneaker", "casual", "retro", "everyday"]),
    dict(sku="SHOE-011", brand="Asics", name="Gel-Kayano 31", type="sport", color="black/red",
         price=12999, sizes=[(7,4),(8,5),(9,4),(10,1)],
         description="Stability running shoe with gel cushioning, ideal for long-distance runners.",
         tags=["running", "stability", "long-distance", "cushioned"]),
    dict(sku="SHOE-012", brand="Skechers", name="Go Walk Flex", type="casual", color="grey",
         price=3999, sizes=[(6,8),(7,9),(8,7)],
         description="Ultra-light slip-on walking shoe designed for all-day comfort.",
         tags=["walking", "comfort", "lightweight", "slip-on"]),
    dict(sku="SHOE-013", brand="Woodland", name="Trail Explorer GB", type="outdoor", color="brown",
         price=6999, sizes=[(7,6),(8,7),(9,5),(10,3)],
         description="Rugged outdoor shoe with reinforced grip, built for trekking and rough terrain.",
         tags=["outdoor", "trekking", "rugged", "grip"]),
    dict(sku="SHOE-014", brand="Bata", name="Comfit Formal Slip-on", type="formal", color="black",
         price=2499, sizes=[(7,5),(8,6),(9,4)],
         description="Comfortable formal slip-on shoe suited for office and daily wear.",
         tags=["formal", "office", "slip-on", "budget"]),
    dict(sku="SHOE-015", brand="Campus", name="Oxy Running Shoe", type="sport", color="royal blue",
         price=1799, sizes=[(6,10),(7,9),(8,8),(9,6)],
         description="Affordable everyday running shoe, a solid budget pick for casual training.",
         tags=["running", "budget", "everyday", "value"]),
    dict(sku="SHOE-016", brand="One8 X Puma", name="One8 Virat Kohli Runner", type="sport", color="black/red",
         price=4999, sizes=[(7,4),(8,6),(9,5),(10,2)],
         description="Performance running shoe from Virat Kohli's One8 line with Puma, built for training runs.",
         tags=["running", "training", "celebrity-collab", "performance"]),
    dict(sku="SHOE-017", brand="One8 X Puma", name="One8 Casual Sneaker", type="casual", color="white/black",
         price=3499, sizes=[(6,5),(7,7),(8,6)],
         description="Everyday casual sneaker from the One8 X Puma collaboration line.",
         tags=["sneaker", "casual", "celebrity-collab", "everyday"]),
]

catalog = []
for i, p in enumerate(products, start=1):
    sizes = [{"size": s, "stock": st} for s, st in p["sizes"]]
    total_stock = sum(st for _, st in p["sizes"])
    slug = p["name"].lower().replace(" ", "+").replace("/", "-")
    catalog.append({
        "id": i,
        "sku": p["sku"],
        "brand": p["brand"],
        "name": p["name"],
        "type": p["type"],
        "color": p["color"],
        "currency": "INR",
        "price": p["price"],
        "in_stock": total_stock > 0,
        "total_stock": total_stock,
        "sizes": sizes,
        "description": p["description"],
        "tags": p["tags"],
        "image_url": f"https://via.placeholder.com/500x500.png?text={slug}"
    })

with open("products.json", "w") as f:
    json.dump(catalog, f, indent=2)

print(f"Wrote {len(catalog)} products to products.json")